# Agradecimientos {.unnumbered}

Este libro ha sido financiado por la Fundación Garfield Weston (<abbr title="Fundación Garfield Weston">GWF</abbr>) como parte del proyecto "Salvaguardando los bosques amenazados de La Española en la República Dominicana", en el marco del proyecto Global Tree Seed Bank (<abbr title="Global Tree Seed Bank, Banco Mundial de Semillas de Árboles">GTSB</abbr>, Banco Mundial de Semillas de Árboles) liderado por Royal Botanic Gardens, Kew (<abbr title="Royal Botanic Gardens Kew (Jardínes Botánicos Reales de Kew)">RBG Kew</abbr>).

El proyecto en la República Dominicana se ha llevado a cabo con el Jardín Botánico Nacional Dr. Rafael M. Moscoso de Santo Domingo (<abbr title="Jardín Botánico Nacional">JBN</abbr>) durante 2015 -- 2020. Los editores y coautores de este libro están profundamente agradecidos con <abbr title="Fundación Garfield Weston">GWF</abbr>, que ha permitido realizar el proyecto, que ha incluido la compilación de la información y publicación de este libro.

Nos gustaría agradecer a todos nuestros colegas de <abbr title="Royal Botanic Gardens Kew (Jardínes Botánicos Reales de Kew)">RBG Kew</abbr> y <abbr title="Jardín Botánico Nacional">JBN</abbr> que ayudaron con las actividades de recolección, conservación, propagación e investigación de las semillas. En particular, nos gustaría agradecer al Dr. Efisio Mattana, Michael Way, David Coleshill, Keith Manger, Prof. Hugh Pritchard y Alice di Sacco del equipo de Kew en Wakehurst y a todo el equipo del <abbr title="Jardín Botánico Nacional">JBN</abbr>, en particular a Pedro Toribio, Wilvin Agramonte y Marianny Terrero por su invaluable contribución, además de agradecer los valiosos comentarios de Milciades Mejía. También agradecemos la ayuda y el apoyo de las comunidades y autoridades locales en la República Dominicana durante las expediciones de recolecta de las semillas.

Finalmente, nos gustaría agradecer a nuestra colega Sharon Balding, coordinadora del <abbr title="Global Tree Seed Bank, Banco Mundial de Semillas de Árboles">GTSB</abbr> por su apoyo en el proyecto dentro de <abbr title="Royal Botanic Gardens Kew (Jardínes Botánicos Reales de Kew)">RBG Kew</abbr>, y Kew Foundation, en particular a Lydia Barnes, quien facilitó la comunicación e interacción con <abbr title="Fundación Garfield Weston">GWF</abbr>.

Muy lamentablemente Brígido Peguero (†), jefe del departamento de Botánica, científico y taxónomo en el <abbr title="Jardín Botánico Nacional">JBN</abbr>, coeditor y coautor de este trabajo, falleció repentinamente antes de la publicación final de este libro. Queremos agradecer a Don Brígido su inestimable contribución y dedicación desde las primeras etapas del proyecto y también dedicar este libro a su familia y compañeros del <abbr title="Jardín Botánico Nacional">JBN</abbr>.
