# Descargo de responsabilidad {.unnumbered}

Este libro contiene información sobre cómo se usan comúnmente las plantas, que incluye información objetiva sobre usos medicinales, culinarios y a base de hierbas, autores y publicadores no aceptan responsabilidad por ningún daño o efecto adverso que surja de cualquier uso de las plantas como se describe.

Siempre debe tomarse consejo médico profesional antes de tomar medicamentos para una enfermedad. Este libro está dirigido a profesionales de la silvicultura y forestales que están asociados con instituciones gubernamentales o no gubernamentales que trabajan en la República Dominicana y Haití. Con este libro proponemos demostrar el uso de especies nativas de árboles silvestres con multiusos que son importantes para el sustento de las comunidades locales y que pueden incluirse en programas de propagación para la reforestación y restauración, así como los medios de vida. Los editores y autores han realizado todos los esfuerzos razonables para rastrear a los propietarios de los derechos de autor de las imágenes reproducidas en este libro.
