# Edición del libro {.unnumbered}

**Editores**

Elena Castillo-Lorenzo (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>), Brígido Peguero (†) (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>) y Tiziana Ulian (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>).

**Contacto de los editores**

Elena Castillo-Lorenzo, Future Leader Fellowship, Royal Botanic Gardens, Kew (Reino Unido)
[e.castillolorenzo\@kew.org](mailto:e.castillolorenzo@kew.org){.email}

Tiziana Ulian , Senior Research Leader, Royal Botanic Gardens, Kew (Reino Unido)
[t.ulian\@kew.org](mailto:t.ulian@kew.org){.email}

**Editor científico**

Fabio Ávila (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>)

**Autores**

Elena Castillo-Lorenzo (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>), Brígido Peguero (†) (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Francisco Jiménez (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Wilkin Encarnación (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Pablo Gómez Barreiro (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>), Teodoro Clase (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Ricardo García (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>) y Tiziana Ulian (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>).

**Fotógrafos**

Pablo Gómez Barreiro (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>), Francisco Jiménez (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>),  Brígido Peguero (†) (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Wilkin Encarnación (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Teodoro Clase (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>), Yommi Piña (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>) y María Caridad Novas (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>). 

**Adaptación y edición en línea**

Pablo Gómez Barreiro (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>)

**Instituciones involucradas**

-   Royal Botanic Gardens, Kew, Reino Unido (<abbr title="Royal Botanic Gardens Kew (El Real Jardín Botánico de Kew)">RBG Kew</abbr>)
-   Jardín Botánico Nacional "Dr. Rafael M. Moscoso", Santo Domingo, República Dominicana (<abbr title="Jardín Botánico Nacional Dr. Rafael M. Moscoso">JBN</abbr>)

**Sugerencia de referencia del libro**

Castillo-Lorenzo, E., Peguero, B., Ulian, T. (eds.) (2022) *Árboles autóctonos de la República Dominicana: Conservación de semillas y propagación para una reforestación sustentable*. Publicado en Santo Domingo, RD.
