# Prólogo {-}

BIODIVERSIDAD Y CAMBIO CLIMÁTICO, MEDIDA DE SOSTENIBILIDAD PARA LOS PAISES EN VÍA DE DESARROLLO.

En el año 1991, mientras cursaba estudio de maestría en la universidad de Texas A&M, tuve el honor de participar en una conferencia, dictada por el Dr. Norman Borlaug, para entonces Premio Nobel de la agricultura por sus aportes a la llamada revolución verde. Mientras el Dr. Borlaug disertaba, ansiosamente levante la mano y le pregunte "Por qué la Revolución Verde había fracasado en África Subsahariana y en la mayoría de los países Latinoamericanos". Su respuesta fue sencilla y me dijo que "La Revolución Verde, es una tecnología que requiere que los países que la adopten apliquen un paquete tecnológico que responda a esta. Es decir, los gobiernos, los investigadores y más que nada los agricultores, deben ser educados para estar al nivel de la circunstancia que este modelo requiere. Cito como ejemplo, que una planta de tomate genéticamente modificada debe contar con tecnología de irrigación, fertilización y de manejo fitosanitario diferente a una planta de tomate endémica.

A partir de esta reflexión debemos considerar la importancia de nuestra fauna y flora nativa. Estas tienen cientos de años en su hábitat natural y la hacen menos vulnerable a los estragos de la realidad del cambio climático, como son sequías e inundaciones.

La relación del Reino Unido y República Dominicana ha sido por años muy exitosa, especialmente la relación que existe entre el Royal Botanic Gardens- Kew y el Jardín Botánico Nacional- Dr. Rafael M.Moscoso. El Kew Garden ha hecho aportes importantes en lo que se refiere a la identificación, producción y preservación de semillas de plantas endémicas, las cuales tienen un gran valor en la reforestación de un país afectado grandemente por la constante tala y quema de los bosques. Un ejemplo de esto es la importancia que tiene la identificación y selección de árboles de *pinus occidentalis* para la producción de éste en los viveros forestales. Este árbol es de extrema importancia en la reforestación de la parte alta de la isla ya que ha mostrado una gran adaptación y desarrollo.

Es importante destacar que la relación de cooperación entre ambas entidades, trasciende y favorece el desarrollo de árboles para ser usados en nuestro país vecino, Haití. Al igual que República Dominicana, Haití también sufre fuertemente los estragos de la deforestación. Podemos decir y confirmar que la deforestación en Haití, supera con creces a la de la República Dominicana. Haití registra alrededor de un 95 por ciento de su territorio deforestado, mientras que República Dominicana registra alrededor de 60% de sus tierras deforestada. La protección de los bosques se traduce en la protección de los recursos naturales como el agua y los propios suelos que son la base para la sobrevivencia humana.

La importancia de un banco de semillas de variedades endémica en los países en vía de desarrollo es de vital importancia para mantener especies resistentes, esto es porque ya han sido naturalmente seleccionadas a través del tiempo y no necesitan ningún nivel de adaptación.

Sin duda alguna, todo el esfuerzo que se haga, tiene que ser a nivel global. No basta con enfocarnos en un área específica, pues todo el planeta esta compelido a enfrentar las consecuencias del cambio climático. Sin embargo, aunque los efectos de esto abarquen a todo el planeta, hay áreas más sensibles y vulnerables. Tenemos una gran preocupación por el deshielo del ártico y el de los glaciares en los mares, pero igual preocupación debe provocar los frecuentes huracanes, inundaciones y tornados que se registran en América Central y el Caribe.

Los frecuentes huracanes causan en el Caribe y Centro América cuantiosos daños materiales, además de daños irreparables de vida humana y animal. Las inundaciones y los vientos huracanados no dejan que los países de a región puedan desarrollar una economía a ritmo sostenible. Cabe destacar que un año de bonanza, puede ser eliminado por el siguiente año, trayendo tragedia humana y perdidas económicas incuantificables. A esto debemos agregarle, la poca capacidad económica y logística, que tienen estos países para afrontar y manejar tales desastres.

La biodiversidad como tal es la base para mantener el ecosistema equilibrado y por ende el pilar para poder producir alimentos para un mundo constantemente castigado por las hambrunas. Basta como ejemplo la falta de nutrición que afecta a muchos países en desarrollo por la escasez de alimentos.

**Embajador Elnio Manuel Durán**
