# Referencias {-}

Agustín, J.A. y Segura Ledesma, S.D. (2014). Conservación y uso de los recursos genéticos de Annonaceae en México. SciELO, v.36, p.118-124.

Ávarez, R., Quintero, I., Manzano Méndez, J., Gónzalez, D. (2009). Emergencia y características de plántulas de Chrysophyllum cainito L. (Sapotacea) bajo diferentes tratamientos pregerminativos y posición de siembra de la planta. Revista Científica UDO Agricola. Vol. 9 No. 2 333-342.

Biblioteca Digital Real Jardín Botánico - CSIC bibdigital.rjb.csic.es

Biodiversidad de Nicaragua. http://www.bio-nica.info/Biblioteca/BibliPlantas.htm

Boletín técnico de biodiversidad. (2010). Manejo de las semillas y la propagación de diez especies forestales del Bosque Andino. No 1. ISSN: 20 11 - 4087.

Cámara, R., Martínez, J. R., & Díaz del Olmo, F. (2005). Desarrollo Sostenible y Medio Ambiente en República Dominicana: Medios Naturales, Manejo Histórico, Conservación y Protección. Sevilla, Escuela de Estudios Hispano-Americanos (CSIC), Universidad de Sevilla.

CEDAF, http://www.cedaf.org.do/arboles_dominicanos/. Accedido Septiembre 2017.

CONABIO. 2017. Sistema Nacional de Información sobre Biodiversidad. Comisión Nacional para el Conocimiento y Uso de la Biodiversidad, México.
CONAFOR. https://www.gob.mx/conafor

CTFS, Center for Tropical Forest Science. http://ctfs.si.edu/webatlas/ Accedido en Septiembre 2017.

FAO www.fao.org. Accedido en Diciembre 2018.

Font Quer, P. (1953). Diccionario de botánica. Labor. Barcelona.

Francis, John K.; Alemañy, Salvador. 1994. Juglans jamaicensis C. DC. Nogal. SO-ITFSM-73. New Orleans, LA: U.S. Department of Agriculture, Forest Service, Southern Forest Experiment Station. 4 p.

García, R., Peguero, B., Jiménez, F., Veloz, A. & Clase, T. (2016). Lista de plantas Vasculares amenazadas en República Dominicana. Ministerio de Educación Superior Ciencias y Tecnología (Mescyt), Jardín Botánico Nacional de Santo Domingo Dr. Rafael M. Moscoso y Ministerio Medio Ambiente y Recursos Naturales. Santo Domingo, República Dominicana. P.741

García, R., Peguero, B., Veloz, A., Clase, T., & Jiménez, F. (2016). Lista Roja de las Plantas Vasculares Amenazadas en República Dominicana. Jardín Botánico Nacional Dr. Rafael M. Moscoso. Santo Domingo, República Dominicana.

Garrido-Ramirez E. (2010). Efecto de la escarificación mecánica e inmersión en agua caliente, sobre el letargo de semillas de guapinol (Hymenaea courbaril L. Fabaceae).

Gelifus, Frans. (1994). El árbol al servicio del agricultor. Guía de especies. Centro agronómico Tropical de Investigación y Enseñanza, Turrialba, Costa Rica.

Gold, K., & Hay, F. (2014). Identifying desiccation sensistive seeds. Technical information sheet No.10. Royal Botanic Gardens, Kew. London.

Gómez, M., & Toro, J. (2008). Manejo de las semillas y la propagación de diez especies forestales del bosque seco tropical. Boletín técnico de Biodiversidad, No. 3. ISSN 2011 - 4087.

Grandtner, M. M. (2005). Elsevier's Dictionary of Trees: Volume 1: North America. Elsevier.

Hernández Sánchez M. L., Hernández Fuentes, A. D., Elorza Martínez, P., López Herrera, M., López Jiménez, M. A. (2009). Caracterización de frutos de caimito (Chrysophyllum cainito L.) en el estado de Veracruz, México. Revista UDO Agrícola 9 (1): 70-73.

IUCN (2020). The IUCN Red List of Threatened Species. Version 2020. https://www.iucnredlist.org 

Liogier, A. (1995). La Flora de La Española VII. República Dominicana. Universidad Central del Este (UCE). Sampedro de Macorís, República Dominicana.

Liogier, A. (2000). Diccionario Botánico de Nombres Vulgares de La Española. Jardín Botánico Nacional de Santo Domingo. República Dominicana.

Lista de plantas de todas las especies vegetales. www.theplantlist.org. Accedido en Diciembre 2018.

Little, E. L., & Marrero, J. (2001). Árboles comunes de Puerto Rico y las Islas Vírgenes. La Editorial, UPR.

Machado, M. C., & Nassar, J. M. (2007). Boletín de la Sociedad Latinoamericana y del Caribe de Cactáceas y otras Suculentas. Vol 4. No 2. ISSN: 1856-4569.

Mattana, E., Manger, K. R., Way, M. J., Ulian, T., Garcia, R., Encarnacion, W., Clase, T., Peguero, B. and Jimenez, F. (2017) A new seed bank for Hispaniola to support the conservation and sustainable use of the Caribbean native flora. Oryx, 51(3), pp. 394-395.

Mattana, E., Peguero, B., Di Sacco, A., Agramonte, W., Castillo, W. R. E., Jiménez, F., Clase, T., Pritchard, H. W., Gómez-Barreiro, P., Castillo-Lorenzo, E., Way, M. J., García, R. and Ulian, T. (2019) Assessing seed desiccation responses of native trees in the Caribbean. New Forests, pp. 1-17.

Mari Mut, J. A. (2015). El árbol de ceiba. Publicado por edicionesdigitales.info. 36 p.

Medel, R. (2013). Boletín de la Sociedad Latinoamericana y del Caribe de Cactáceas y otras Suculentas. Vol.10. No 2. ISSN: 1856-4569

Mejía M.; R. García, S. Rodríguez & J. Salázar. 2001, Pereskia quisqueyana Alain (Cactaceae) Historia y conservación. Moscosoa 12: 45-53.

Méndez-Gómez, J. (2014). Viabilidad y germinación en semillas de Pimenta dioica (L.) Merril. Revista Científica Biológico Agropecuaria Tuxpan, 2(3), 453-458.

Mesen, F., Rodriguez, Y., & Sanchez, A. (1996). Memorias Primer seminario nacional sobre mejoramiento genetico y semillas forestales. CATIE, Turrialba (Costa Rica). Proyecto de Semillas forestales.

Mora, M. A., & Vargas, M. (2017). El Atlas de la Biodiversidad de Costa Rica (CRBio).

Padrón Vélez, R., & Ricart Pujals, J. (2015). Sinopsis Anotada y Comentada de la Flora del Bosque Estatal de Guilarte. Ediciones y Taller CIBA, Puerto Rico.

Pérez-Hernández, I., Ochoa-Gaona, S.,Vargas-Simón, G., Mendoza-Carranza, M., González-Valdivia, N.A. (2010). Germinación y supervivencia de seis especies nativas de un bosque tropical de Tabasco, México. Madera y Bosques 17(1): 71-91.

Plants of the World online http://www.plantsoftheworldonline.org/. Accedido en Mayo 2020.

Pritchard, H. W., Wood, C. B., Hodges, S., & Vautier, H. J. (2004). 100-seed test for desiccation tolerance and germination: a case study on eight tropical palm species. Seed Science and Technology, 32(2), 393-403.

Programa Protección Ambiental (PPA). Calendario para recolección de semillas de especies forestales (República Dominicana). Tomo I. 2011. Santo Domingo, República Dominicana. 48p.

Programa Protección Ambiental (PPA). Calendario para recolección de semillas de especies forestales (República Dominicana). Tomo II. 2012. Santo Domingo, República Dominicana. 48p.

Programa Protección Ambiental (PPA). Guía de árboles maderables en la República Dominicana. Santo Domingo, República Dominicana. CEDAF, 2012, 216p.

Ricardo, S. M. J., & Duarte, O. (2004). Efecto de la deshidratación sobre la germinación de semillas de caimito (Chrysophyllum cainito L.) y jaca (Artocarpus heterophyllus Lam.) (No. T1933). Escuela Agrícola Panamericana.

Salazar, R., Soihet, C., & Méndez, J. M. (2000). Manejo de semillas de 100 especies forestales de América Latina. Centro Agronómico de Investigación y Enseñanza (CATIE), Turrialba, Costa Rica.

SEMARNAT. 2017. Secretaría de Medio Ambiente y Recursos Naturales de México. Protección ambiental - especies nativas de México de flora y fauna silvestres - Categorías de riesgo y especificaciones para su inclusión, exclusión o cambio - Lista de especies en riesgo. Mexico City: Diario Oficial.

Sosa, J. L. R., & Espinosa, C. A. (2013). Germinación de Juglans jamaicensis C. DC. subsp. jamaicensis, en vivero. Revista Cubana de Ciencias Forestales: CFORES, 1(1), 94-101.

Sosa Méndez, J. (2004). Efecto de la deshidratación sobre la germinación de semillas de caimito (Chrysophyllum cainito L.) y jaca (Artocarpus heterophyllus Lam.). Proyecto para de Ingeniero Agrónomo en el Grado Académico de Licenciatura. Carrera de Ciencia y Producción Agropecuaria. Universidad de Zamorano, Honduras. 12pp.

Trópicos. http://www.tropicos.org/Home. Accedido en Diciembre 2018.

Vozzo, J.A. (2011). Manual de semillas de árboles tropicales. Departamento de Agricultura de los Estados Unidos, USDA Forest Service, Washington DC.